import { useState } from 'react'
import ResumeUpload from './components/ResumeUpload'
import JDInput from './components/JDInput'
import FitScore from './components/FitScore'
import GapAnalysis from './components/GapAnalysis'
import SectionCard from './components/SectionCard'
import HistoryPanel from './components/HistoryPanel'

function App() {
  const [resume, setResume] = useState(null)
  const [analysis, setAnalysis] = useState(null)
  const [analyzing, setAnalyzing] = useState(false)
  const [error, setError] = useState(null)

  const handleAnalysisComplete = (result) => {
    setAnalysis(result)
    setError(null)
  }

  const handleError = (message) => {
    setError(message)
    setAnalyzing(false)
  }

  const handleExport = () => {
    if (!analysis) return

    const lines = []
    lines.push('TAILORED RESUME SUGGESTIONS')
    lines.push('Generated by SmartApply')
    lines.push('='.repeat(50))
    lines.push('')

    analysis.sections.forEach(section => {
      lines.push(section.section_title.toUpperCase())
      lines.push('-'.repeat(30))

      if (section.suggestions.length === 0) {
        lines.push('(no changes suggested)')
      } else {
        section.suggestions.forEach(s => {
          lines.push(`Original:  ${s.original}`)
          lines.push(`Improved:  ${s.improved}`)
          lines.push('')
        })
      }
      lines.push('')
    })

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `smartapply_${analysis.id}.txt`
    a.click()
    URL.revokeObjectURL(url)
  } 

  return (
    <div className="min-h-screen bg-gray-100">

      {/* Header */}
      <header className="bg-emerald-100 border-b border-emerald-200 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-left gap-6">
          <button
            onClick={() => setAnalysis(null)}
            className="flex items-center gap-3 hover:opacity-80 transition-opacity text-left"
          >
            <div className="w-8 h-8 bg-emerald-700 rounded-lg flex items-center justify-center flex-shrink-0">
              <span className="text-emerald-50 text-sm font-bold">S</span>
            </div>
            <div className="flex flex-col items-start">
              <h1 className="text-emerald-900 font-medium text-lg leading-none">SmartApply</h1>
              <p className="text-emerald-600 text-xs mt-0.5">AI resume fit analyzer</p>
            </div>
          </button>

          {resume && (
            <div className="flex items-center gap-2 bg-white border border-emerald-200 rounded-full px-3 py-1.5">
              <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full" />
              <span className="text-emerald-700 text-xs">{resume.filename}</span>
            </div>
          )}
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8">
        {error && (
          <div className="mb-6 bg-red-50 border border-red-200 rounded-xl px-4 py-3 text-red-600 text-sm">
            ⚠ {error}
          </div>
        )}

        {!analysis && (
          <div className="flex flex-col gap-4">
            <div className="grid grid-cols-2 gap-4">
              <ResumeUpload onUpload={setResume} onError={handleError} resume={resume} analyzing={analyzing} />
              <JDInput resume={resume} onAnalyzing={setAnalyzing} onComplete={handleAnalysisComplete} onError={handleError} analyzing={analyzing} />
            </div>
            <HistoryPanel onSelect={setAnalysis} />
          </div>
        )}

        {analysis && (
          <div className="flex flex-col gap-4">
            <div className="flex items-center justify-between">
              <button
                onClick={() => setAnalysis(null)}
                className="text-emerald-600 hover:text-emerald-800 text-sm transition-colors"
              >
                ← New analysis
              </button>
              <div className="text-right">
                <p className="text-gray-800 text-sm font-medium">
                  {analysis.company_name}
                  {analysis.role && <span className="text-gray-500 font-normal"> · {analysis.role}</span>}
                </p>
                <p className="text-gray-400 text-xs">Analysis #{analysis.id}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <FitScore score={analysis.fit_score} summary={analysis.summary} />
              <GapAnalysis matchingSkills={analysis.matching_skills} missingKeywords={analysis.missing_keywords} />
            </div>

            <div>
              <div className="flex items-center gap-3 mb-3">
                <h2 className="text-gray-800 font-medium">Section suggestions</h2>
                <span className="bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs px-2.5 py-0.5 rounded-full">
                  {analysis.sections.filter(s => s.suggestions.length > 0).length} to improve
                </span>
              </div>
              <div className="flex flex-col gap-3">
                {analysis.sections.map(section => (
                  <SectionCard
                    key={section.section_type}
                    section={section}
                    analysisId={analysis.id}
                  />
                ))}
              </div>
            </div>

            {/* Export button */}
            <div className="flex justify-end pt-2">
              <button
                onClick={handleExport}
                className="bg-emerald-700 hover:bg-emerald-800 text-white text-sm font-medium px-5 py-2.5 rounded-lg transition-colors flex items-center gap-2"
              >
                ↓ Export suggestions
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

export default App